config/routes.rb
Rails.application.routes.draw do
  get  'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'welcome#index'

  resources :sessions, only: [:create, :destroy]

  resources :boards do
    resources :tasks, only: [:create, :destroy, :edit, :update] do
      put :sort, on: :collection
    end
  end
  

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  validates :name, :uid, presence: true
  validates_associated :tasks

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :board
  validates :body, presence: true
  validates :status, inclusion:  { in: %w(todo doing done) }
  default_scope {order("priority ASC")}
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :valid_login?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def valid_login?
    if current_user
      !current_user.oauth_expires_at.past?
    else
      false
    end
  end

  def owns_board(board_id)
    board = Board.find(board_id)
    current_user.uid == board.uid
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout 'application'

  def index
    if valid_login?
      if params[:search]
        @boards = Board.search(params[:search]).where("uid = ?", current_user.uid).order("created_at DESC")
      else
        @boards = Board.where("uid = ?", current_user.uid).order("created_at DESC")
      end
    else
      flash[:expired] = true
      redirect_to signout_path
    end
  end

  def show
    if valid_login?
      if owns_board(params[:id])
        @board = Board.find(params[:id])
        @todo = @board.tasks.select {|task| task.status == 'todo'}
        @doing = @board.tasks.select {|task| task.status == 'doing'}
        @done = @board.tasks.select {|task| task.status == 'done'}
      else
        redirect_to boards_path
      end
    else
      flash[:expired] = true
      redirect_to signout_path
    end
  end

  def new
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def edit
    @board = Board.find(params[:id])
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def create
    if valid_login?
      @board = Board.new(board_params)
      respond_to do |format|
        if @board.save
          format.js {}
          format.html { redirect_to @board }
        else
          format.js { render :new }
          format.html { render :new }
        end
      end
    else
      flash[:expired] = true
      redirect_to signout_path
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  def update
    if valid_login?
      @board = Board.find(params[:id])
      respond_to do |format|
        if @board.update(board_params)
          format.js {}
          format.html { redirect_to board_path(@board) }
        else
          format.js { render :edit }
          format.html { render :edit }
        end
      end
    end
  end

  private

  def board_params
    params.require(:board).permit(:name).merge({"uid" => current_user.uid})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    reset_session
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to boards_path
  end

  def destroy
    session[:user_id] = nil
    reset_session
    if flash[:expired]
      flash[:message] = "Login expired. Please login again to keep working."
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    if valid_login?
      @board = Board.find(params[:board_id])
      new_task_pos = @board.tasks.select {|task| task.status == params[:task][:status]}.length + 1
      @task = @board.tasks.create(task_params)
      @task.priority = new_task_pos
    
      respond_to do |format|
        if @task.save
          format.js {}
          format.html { redirect_to board_path(@board), notice: 'Task was saved.' }
        else
          format.html { redirect_to board_path(@board), notice: 'Task could not be saved.' }
        end
      end
    else
      flash[:expired] = true
      redirect_to signout_path
    end
  end

  def destroy
    if valid_login?
      @board = Board.find(params[:board_id])
      @task = @board.tasks.find(params[:id])
      respond_to do |format|
        if @task.destroy
          format.js {}
          format.html { redirect_to board_path(@board), notice: 'Task was deleted.' }
        else
          format.html { redirect_to board_path(@board), notice: 'Task was  not deleted.' }
        end
      end
    else
      flash[:expired] = true
      redirect_to signout_path
    end
  end
 
  def edit
    if valid_login?
      @board = Board.find(params[:board_id])
      @task = @board.tasks.find(params[:id])
      respond_to do |format|
        format.js {}
        format.html {}
      end
    else
      flash[:expired] = true
      redirect_to signout_path
    end
  end

  def sort
    params[:order].each do |_, task|
      Task.find(task[:id]).update_attribute(:priority, task[:position])
    end
    render :nothing => true
  end

  def update
    if valid_login?
      @board = Board.find(params[:board_id])
      @task = @board.tasks.find(params[:id])
      respond_to do |format|
        if @task.update task_params
          format.js {}
          format.html { redirect_to board_path(@board) }
        else
          format.js { render :edit }
          format.html { render :edit }
        end
      end
    else
      flash[:expired] = true
      redirect_to signout_path
    end
  end
    
  private

  def task_params
    params.require(:task).permit(:body, :status)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'application'

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/_boards.html.erb
<% boards.in_groups_of 3 do |group| %>
	<div class="row">
		<% group.compact.each do |board| %>
			<div class="col-md-4">
				<div class="square">
					<%= link_to board do %>
						<span class="link-spanner"><%= board.name %></span>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/boards/_create.html.erb
<%= form_for :board, url: boards_path, remote: true, html: {role: "form", class: "board-form", name: "form"} do |f| %>
	<%= image_tag "3.png", class: "close-form-img", id: "close-img"%>
	<h2>Create Board</h2>
	<hr>
	<div class="form-group">
		<%= f.text_field :name, class: "form-control", id: "board-name", placeholder: "Board Name"%>
	</div>
	<button type="submit" class="btn btn-default form-button">Create</button>
<% end %>

app/views/boards/_update.html.erb
<%= form_for :board, url: board_path(board), method: :patch, remote: true, html: {role: "form", class: "board-form", name: "form"} do |f| %>
	<%= image_tag "3.png", class: "close-form-img", id: "close-img"%>
	<h2>Rename Board</h2>
	<hr>
	<div class="form-group">
		<%= f.text_field :name, class: "form-control", id: "board-name", placeholder: "Board Name"%>
	</div>
	<button type="submit" class="btn btn-default form-button">Rename</button>
<% end %>

app/views/boards/create.js.erb
var path = '/boards/' + '<%= @board.id %>';
window.location.replace(path);

app/views/boards/edit.html.erb
<%= render partial: "update", locals: { board: @board } %>

app/views/boards/edit.js.erb
$(".popup-form").html("<%= j (render partial: 'update', locals: { board: @board }) %>");
showPopUpForm();
$(".close-form-img").click(function() {
	closePopUpForm();
	$(".popup-form").html("<%= j (render partial: 'create') %>");
	closeImgBind();
});

app/views/boards/index.html.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "board" %>
<% end %>

<%= content_for :body do %>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<%= form_tag boards_path, :method => 'get', :class => "navbar-form navbar-left", :role => "search", :id => "boards_search" do %>
				<div class="form-group">
					<%= search_field_tag :search, params[:search], :placeholder => "Board Name", :class => "form-control", :id => "search-field" %>
				</div>
				<%= submit_tag "Search", :class => "btn btn-default" %>
			<% end %>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_url %></li>
					<li><%= link_to "Code", "https://github.com/KarlParkinson/ScrumBoard" %></li>
					<li><%= link_to "New", new_board_path, :id => 'new-board-link', :remote => true %></li>
					<li><%= link_to "Sign Out", signout_path %></li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container" id="boards_region">
		<%= render partial: "boards", locals: {boards: @boards} %>
	</div>

	<div class="form-container" id="form-container">
		<div class="popup-form">
			<%= render partial: "create" %>
		</div>
	</div>

<% end %>

app/views/boards/index.js.erb
$("#boards_region").html("<%= escape_javascript(render partial: "boards", locals: {boards: @boards}) %>")

app/views/boards/new.html.erb
<div class="container">
	<%= form_for :board, url: boards_path, html: {role: "form"} do |f| %>
		<div class="form-group">
			<%= f.label :name, "Board Name" %>
			<br>
			<%= f.text_field :name, class: "form control" %>
		</div>
		<button type="submit" class="btn btn-default">Create</button>
	<% end %>
</div>
	
		

app/views/boards/new.js.erb
$(".popup-form").html("<%= j (render partial: 'create') %>");
showPopUpForm();
$(".close-form-img").click(function() {
	closePopUpForm();
	$(".popup-form").html("<%= j (render partial: 'create') %>");
	closeImgBind();
});

app/views/boards/show.html.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "board" %>
<% end %>

<%= content_for :body do %>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<h4 class="navbar-text" id="board-name"><%= @board.name %></h4>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_url %></li>
					<li><%= link_to "Rename", edit_board_path,  remote: true %></li>
					<li><%= link_to "Delete", board_path(@board), method: :delete, data: { confirm: 'Are you sure?'} %></li>
					<li><%= link_to "Code", "https://github.com/KarlParkinson/ScrumBoard" %></li>
					<li><%= link_to "New", new_board_path, remote: true %></li>
					<li><%= link_to "Boards", boards_path %></li>
					<li><%= link_to "Sign Out", signout_path %></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<div class="flex-container">
		<div class="column" id="todo">
			<h3>TODO</h3>
			<ul id="todo-tasks-container" class="sortable connected-sortable task-list">
				<% @todo.each do |task| %>
					<%= render partial: "tasks/task", locals: {task: task} %>
				<% end %>
			</ul>
			<%= render partial: "tasks/form", locals: {board: @board, column: 'todo'} %>
		</div>
		<div class="column" id="doing">
			<h3>DOING</h3>
			<ul id="doing-tasks-container" class="sortable connected-sortable task-list">
				<% @doing.each do |task| %>
					<%= render partial: "tasks/task", locals: {task: task} %>
				<% end %>
			</ul>
			<%= render partial: "tasks/form", locals: {board: @board, column: 'doing'} %>
		</div>
		<div class="column" id="done">
			<h3>DONE</h3>
			<ul id="done-tasks-container" class="sortable connected-sortable task-list">
				<% @done.each do |task| %>
					<%= render partial: "tasks/task", locals: {task: task} %>
				<% end %>
			</ul>
			<%= render partial: "tasks/form", locals: {board: @board, column: 'done'} %>
		</div>
	</div>

	<div class="form-container" id="create-form-container">
		<div class="popup-form">
			<%= render partial: "create" %>
		</div>
	</div>

<% end %>

app/views/boards/update.js.erb
$("#board-name").html("<%= @board.name %>");
closePopUpForm();
$(".popup-form").html("<%= j (render partial: 'create') %>");
closeImgBind();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>ScrumBoard</title>
		<%= stylesheet_link_tag "bootstrap.min.css"%>
		<%= javascript_include_tag "bootstrap.min.js" %>
		<%= yield :head %>
		<!-- - <#%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>-->
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<!-- -<#%= csrf_meta_tags %>-->
	</head>
	<body>

		<%= yield :body %>

	</body>
</html>

app/views/layouts/boards.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrumBoard</title>
    <%= stylesheet_link_tag "bootstrap.min.css"%>
    <%= javascript_include_tag "bootstrap.min.js" %>
  </head>
  <body>

    <%= yield %>
    
  </body>
</html

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>ScrumBoard</title>
		<%= stylesheet_link_tag "bootstrap.min.css", "welcome" %>
		<%= javascript_include_tag "bootstrap.min.js" %>
	</head>
	<body>

		<%= yield %>
		
	</body>
</html

app/views/tasks/_edit.html.erb
<%= form_for :task, url: board_task_path, method: :patch, remote: true, html: {role: "form", class: "board-form", name: "form"} do |f| %>
	<%= image_tag "3.png", class: "close-form-img", id: "close-img"%>
	<h2>Edit Task</h2>
	<hr>
	<div class="form-group">
		<%= f.text_area :body, class: "form-control", id: 'task-description'%>
	</div>
	<button type="submit" class="btn btn-default form-button">Save</button>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for [board, board.tasks.build], html: {role: "form", class: "form", name: "form"}, remote: true do |f| %>
	<div class="form-group">
		<%= f.text_area :body, class: "form-control" , id: "task-body-#{column}", placeholder: "New Task" %>
	</div>
	<div class="radio" style="display:none;">
		<%= f.radio_button :status, column, :checked => true %>
	</div>
	<button type="submit" class="btn btn-default form-button">Create</button>
<% end %>

app/views/tasks/_task.html.erb
<li class="task-list-entry" data-id="<%= task.id %>" data-cat="<%= task.status %>" pos="<%= task.priority %>">
	<div class="content">
		<span class="edit-delete">
			<%= link_to "Edit", edit_board_task_path(task.board_id, task.id), remote: true %>
			<%= link_to "Delete", [task.board, task], remote: true, method: :delete, data: { confirm: 'Are you sure?'} %>
		</span>
		<div id="<%= task.id %>-body-div">
			<%= render partial: 'tasks/task_body', locals: {task: task} %>
		</div>
	</div>
</li>

app/views/tasks/_task_body.html.erb
<pre class="task", id="<%= task.id %>-body"><br><%= task.body %><br><br></pre>

app/views/tasks/create.js.erb
$('#<%= @task.status %>-tasks-container').append("<%= j (render @task) %>");
console.log("hello");
$('#task-body-<%= @task.status %>').val('');
mouseHoverBind();

app/views/tasks/destroy.js.erb
$("[data-id|='<%= @task.id %>']").remove();

app/views/tasks/edit.html.erb
<%= render partial: 'edit' %>

app/views/tasks/edit.js.erb
$(".popup-form").html("<%= j (render partial: 'edit') %>");
showPopUpForm();
$(".close-form-img").click(function() {
	closePopUpForm();
	$(".popup-form").html("<%= j (render partial: 'boards/create') %>");
	closeImgBind();
});

app/views/tasks/update.js.erb
var task = $("#<%= @task.status %>-tasks-container").find("[data-id|='<%= @task.id %>']");
task.attr("data-cat", "<%= @task.status %>");
task.attr("pos", "<%= @task.priority %>");
$("#<%= @task.id %>-body-div").html("<%= j (render partial: 'task_body', locals: {task: @task}) %>");
closePopUpForm();
$(".popup-form").html("<%= j (render partial: 'boards/create') %>");
closeImgBind();

app/views/welcome/index.html.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "welcome" %>
<% end %>

<%= content_for :body do %>

	<div class="site-wrapper">
		<div class="site-wrapper-inner">
			<div class="cover-container">
				<div class="masthead clearfix">
					<div class="inner">
						<h3 class="masthead-brand">ScrumBoard</h3>
						
						<ul class="nav masthead-nav">
							<li>
								<a href="https://github.com/KarlParkinson/ScrumBoard" target="_blank"><h3 class="masthead-brand">Code</h3></a>
							</li>
						</ul>
					</div>
				</div>
				
				<div class="form-container" id="form-container">
					<div class="popup-form">
						<%= render partial: "boards/create" %>
					</div>
				</div>
								
				<div class="inner cover">
					<h1 class="cover-heading">A Simple, Free Scrum Board.</h1>
					
					<p class="lead">ScrumBoard is a simple, free Ruby on Rails application that allows you to organize any project you wish.</p>

					<p class="lead">
						<!--<button class="btn btn-lg btn-info" id="my-link">Get Started</button>-->
						<%= link_to "Sign In With Google To Get Started", "/auth/google_oauth2", class: "btn btn-lg btn-info" %>
					</p>
				</div>

				<div class="mastfoot">
					<div class="inner">
						
						<p><a href="http://rubyonrails.org/" target="_blank"><small>Powered By Rails</small></a></p>
						
					</div>
				</div>
			</div>
		</div>
	</div>

	<% if flash[:message] %>
		<script>
		alert("<%= flash[:message] %>");
		</script>
	<% end %>
	
<% end %>